local status, _ = pcall(vim.cmd, "colorscheme onedark")
if not status then
	return
end

require("onedark").setup({
	style = "deep",
	transparent = true,
	colors = {
		red = "#EA4444",
		yellow = "#FFFF00",
		blue = "#52B9FF",
		sky_blue = "#07CDDF",
		purple = "#722099",
		lime = "#51E800",
		cyan = "#00FFD5",
		orange = "#FCB103",
		-- muddy_green = "#91A165",
		faint_green = "#9ABF8E",
		faint_orange = "#E0Ca67",
		numbers_blue = "#78D0EB",
		royal_blue = "#0044B3",
	},
	highlights = {
		-- ["@annotation"] = colors.Fg,
		-- ["@attribute"] = colors.Cyan,
		["@boolean"] = { fg = "$red" },
		-- ["@character"] = colors.Orange,
		["@comment"] = { fg = "$purple" },
		["@conditional"] = { fg = "$red" },
		["@constant"] = { fg = "$yellow" },
		["@constant.builtin"] = { fg = "$orange" },
		["@constant.macro"] = { fg = "$orange" },
		["@constructor"] = { fg = "$sky_blue" },
		["@error"] = { fg = "$yellow" },
		["@exception"] = { fg = "$yellow" },
		-- ["@field"] = colors.Cyan,
		["@float"] = { fg = "$numbers_blue" },
		["@function"] = { fg = "$lime" },
		["@function.builtin"] = { fg = "$lime" },
		["@function.macro"] = { fg = "$lime" },
		["@include"] = { fg = "$orange" },
		["@keyword"] = { fg = "$red" },
		["@keyword.function"] = { fg = "$red" },
		["@keyword.operator"] = { fg = "$orange" },
		-- ["@label"] = colors.Red,
		["@method"] = { fg = "$lime" },
		["@namespace"] = { fg = "$orange" },
		-- ["@none"] = colors.Fg,
		["@number"] = { fg = "$numbers_blue" },
		["@operator"] = { fg = "$faint_orange" },
		["@parameter"] = { fg = "$cyan" },
		-- ["@parameter.reference"] = colors.Fg,
		-- ["@property"] = colors.Cyan,
		["@punctuation.delimiter"] = { fg = "$faint_orange" },
		["@punctuation.bracket"] = { fg = "$faint_orange" },
		["@punctuation.special"] = { fg = "$faint_orange" },
		-- ["@repeat"] = { fg = c.purple, fmt = cfg.code_style.keywords },
		["@string"] = { fg = "$faint_green" },
		-- ["@string.regex"] = { fg = c.orange, fmt = cfg.code_style.strings },
		-- ["@string.escape"] = { fg = c.red, fmt = cfg.code_style.strings },
		-- ["@symbol"] = colors.Cyan,
		["@tag"] = { fg = "$orange" },
		["@tag.delimiter"] = { fg = "$red" },
		-- ["@text"] = { fg = "$muddy_green" },
		-- ["@text.strong"] = { fg = c.fg, fmt = "bold" },
		-- ["@text.emphasis"] = { fg = c.fg, fmt = "italic" },
		-- ["@text.underline"] = { fg = c.fg, fmt = "underline" },
		-- ["@text.strike"] = { fg = c.fg, fmt = "strikethrough" },
		-- ["@text.title"] = { fg = c.orange, fmt = "bold" },
		-- ["@text.literal"] = colors.Green,
		-- ["@text.uri"] = { fg = c.cyan, fmt = "underline" },
		-- ["@text.math"] = colors.Fg,
		-- ["@text.reference"] = colors.Blue,
		-- ["@text.enviroment"] = colors.Fg,
		-- ["@text.enviroment.name"] = colors.Fg,
		-- ["@note"] = colors.Fg,
		-- ["@warning"] = colors.Fg,
		-- ["@danger"] = colors.Fg,
		["@type"] = { fg = "$sky_blue" },
		["@type.builtin"] = { fg = "$red" },
		["@variable"] = { fg = "$cyan" },
		["@variable.builtin"] = { fg = "$sky_blue" },
	},
})

require("onedark").load()
